spring:
  profiles:
    active: dev
  resources:
    static-locations:
---
web:
  Allpath: http://localhost:8080/yujing
  File_Path: File/images/upload
spring:
  jpa:
    show-sql: true
  resources:
    static-locations: classpath:static/,file:static/
  thymeleaf:
    cache: false
  profiles: dev
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/yujing?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    favicon:
      enabled: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  servlet:
    context-path: /yujing
  port: 8080
mybatis:
  mapper-locations: /mapper/*.xml
logging:
  level:
    cn.cks.studiowebsite.service.PeopleMapper:
      INFO
  path: log